runtime: python39
entrypoint: gunicorn -b :$PORT ProyectoAxon.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'ProyectoAxon.settings'
  SECRET_KEY: 'django-insecure-g*itw42s@mvgp&u&)3-pz99_70s0hqii!#z794!$#x%l-4=8a-'
  GOOGLE_CLOUD_SQL_CONNECTION_NAME: 'axon-426916:us-central1:axondb'

beta_settings:
  cloud_sql_instances: 'axon-426916:us-central1:axondb'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto