runtime: python38
entrypoint: gunicorn -b :$PORT ProyectoAxon.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: 'ProyectoAxon.settings'
  SECRET_KEY: 'django-insecure-g*itw42s@mvgp&u&)3-pz99_70s0hqii!#z794!$#x%l-4=8a-'
  DATABASE_URL: 'mysql://root:''@/axondb?unix_socket=/cloudsql/axon-426916:northamerica-northeast1:axondb'

beta_settings:
  cloud_sql_instances: axon-426916:northamerica-northeast1:axondb

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto